import React from 'react';

const TOU = () => (
  <div className="docs-example-2">
<p class="bodytext">PLEASE READ THIS NOTICE CAREFULLY BEFORE USING THE SITE. IN THIS NOTICE IS DETERMINED THAT YOU MAKE USE OF THE SITE AND ALL MATERIAL ON THE SITE.</p>
<p class="bodytext"><b>General<br /></b>By accessing this site you accept that you are bound by these Terms of Use, so please check these terms of use again each time you approach the site. If you are not willing to observe the content of these terms of use, please do not use this site.</p>
<p class="bodytext">This website (excluding linked sites) is managed by us. You will agree with us that U.S. law applies to all matters that may arise or be related to the use and content of this site.</p>
<p class="bodytext"><b>Copyright (copyright) / Intellectual Property<br /></b>Copyright. All rights reserved. All copyrights and other intellectual property rights in all text, images, sounds, software and other materials on this site are owned by us and its affiliated companies or are used with permission of the owner.</p>
<p class="bodytext">You are allowed to browse this site and to reproduce parts of it by way of printing, downloading to a hard drive or sending copies to others, provided that this is only for informative purposes and the above copyright notice is mentioned in all such copies.</p>
<p class="bodytext">No reproduction of any part of the site may be sold, distributed for commercial purposes, altered or included in any other work or publication, whether in the form of a printed document of an electronic form. This includes sending to other sites, inclusion in another website ("framing") or linking of other sites to this site, unless a prior permission was given. Nor any license or other right is granted.</p>
<p class="bodytext">All trademarks displayed on this site are owned or used under license by us and its affiliates. Use of any trademark displayed on this site is strictly prohibited, unless with written permission by us.</p>
<p class="bodytext"><b>Availability of Products<br /></b>Links on this site to products or services do not constitute an offer to sell or supply that product or service. To purchase a particular product or service a specific advice concerning the availability and suitability should be asked for.</p>
<p class="bodytext"><b>Content<br /></b>The information on this site is provided in good faith, but should only be used for general information purposes. The information can not be legally binding on its reliability for any specific purpose and no representation or warranty regarding the accuracy or completeness is given. The information on this site does not constitute medical, legal or investment advice.</p>
<p class="bodytext">Any liability of this site, its affiliated companies and officers, our affiliated employees or agents and its affiliated companies for any loss, damage or expense arising out of any access or use of this site or any linked site, including lost profits or indirect, incidental or consequential damages, to the extent legally permitted, is excluded.</p>
<p class="bodytext"><b>Changes in the Terms of Use and the site<br /></b>We reserve the right, without notice, to make at any time changes and corrections to this site and to end the access to this site at the time and manner we think it is desirable and necessary.</p>
<p><b>Linked sites<br /></b>At various points throughout the whole site automatic links may have been created to other Internet sites, relevant to a particular aspect of this site. This does not necessarily mean that our organization is linked to these other sites or their owners. While we strive to refer you to crediting 
sites for your convenience, neither our organization nor our affiliates, nor its or their officers, employees or representatives in any way is responsible or liable for these sites and the information on these sites, which is not verified or endorsed by our organization or our affiliates.</p>
<p class="bodytext">If notice at any time that you have accessed another site, you can return to this site by clicking the 'back' arrow button or the domain address of our organization.</p>
<p class="bodytext"><b>Information provided by you<br /></b>By providing information to us or to send us materials you agree that we are allowed to use this information and materials and that we do not violate the rights of third parties by using this information and materials.</p>
<p class="bodytext">We have no control on parts of the site that contain information provided by other users of the site. We accept no responsibility or liability for such information. We reserve the right to delete or correct this information at any given time without prior notice.</p>
<p class="bodytext"><b>Data Protection<br /></b>Personal information that you provide via this site will only be used in accordance with our Privacy Statement. Please read the Privacy Policy carefully before providing us with information.</p>
<p class="bodytext"><b>Contact us<br /></b>If you have a question or complaint about this site, please <a class="internal-link" href="mailto:begreentampa@gmail.com">contact</a> us.</p>
<h1>Disclaimer</h1>
<p class="bodytext">No rights can be derived from the information provided on <a href="https://floridafreeappliancepickup.com/" target="_blank">www.floridafreeappliancepickup.com</a></p>
<p class="bodytext">Florida Free Appliance Pickup has taken the utmost care in developing this website. Information will be updated on a continuous basis in order to give visitors an accurate impression of the available services.</p>
<p class="bodytext">Nevertheless, Florida Free Appliance Pickup cannot guarantee that all the information contained on this website is free of errors, complete or fully up to date. Ergo, Florida Free Appliance Pickup accepts no liability whatsoever for any losses resulting from incorrect or outdated information.</p>
<p class="bodytext">Pages of <a href="https://floridafreeappliancepickup.com/" target="_blank">www.floridafreeappliancepickup.com</a> may contain links to (commercial or non-commercial) institutions and organizations. Florida Free Appliance Pickup accepts no responsibility for the content of these linked sites.
 Links to, or the incorporation of (parts of) this website for commercial reasons is not permitted. Nor may any frames, framesets or frameworks of Florida Free Appliance Pickup be directly incorporated by or linked to any other website. No part of this site may be reproduced, unless for own publication subject to written prior permission of Florida Free Appliance Pickup with obligatory source indication.</p>
<p class="bodytext">For any questions or requests for permission please <a class="internal-link" href="mailto:begreentampa@gmail.com">contact</a> us.</p>
  </div>
);

export default TOU;
